restore:
  bucket_uri: ${bucket_uri}
  file_name: ${file_name}
  aws_default_region: ${s3_bucket_region}

auth:
  username: "${custom_user_username}"

annotations:
  ${annotations}

bucket_provider_type: ${bucket_provider_type}
